### ISSUE TITLE
Document the existence of the Debian repository

### ISSUE THREAD

**Issue by jameshfisher** [elasticsearch/logstash-forwarder#184]
The README describes how I can build and then package logstash-forwarder. However, it would be much more convenient if there were either an archive of deb files, or a Debian/Ubuntu repository. Then I wouldn't have to bother with Ruby, FPM, Go, and any other transient build-time dependencies.

**Comment by burdandrei** [comment]
and today, these repos disappeared  =(

**Comment by jordansissel** [comment]
The repo was delivering know buggy version of lsf for months. I tried to
purge the files a few months ago and thought it was done, but I realized
yesterday that I forgot another place. Fixed it by removing the files.

We will be doing another release of lsf soon.

-Jordan

**Comment by malclocke** [comment]
:disappointed: just went to push a deploy that relied on this repo and now it's 404.  I guess the official line would be not to use it even if it does come back, seeing as it is not publicised?

**Comment by jordansissel** [comment]
@malclocke Mentioned [previously](https://github.com/elasticsearch/logstash-forwarder/issues/184#issuecomment-53475198), the recommendation is to build from master. The package previously known as "logstash-forwarder 0.3.1" was very buggy and caused trouble for so many new users that I purged it.

**Comment by topperge** [comment]
Purging the repo also caused the "official" puppet module to break as well
https://github.com/elasticsearch/puppet-logstashforwarder/blob/master/manifests/repo.pp#L35

**Comment by tomsommer** [comment]
You could also just push 0.3.2 to the repo instead of purging everything? Breaking yum/apt for everyone...

**Comment by deviantony** [comment]
@tomsommer +1

**Comment by volans-** [comment]
@jordansissel as a general rule a non maintained repo is worse than not having a repo at all IMHO.

If you can't maintain it I think you could simply ask the [Debian Developers](https://www.debian.org/devel/) / [Ubuntu MOTU](https://wiki.ubuntu.com/MOTU) teams to try to get an official maintainer for the DEB packages.

As a best practice, to avoid to break other people installations, always better publish the new package **before** deleting the old one.

**Comment by nunogt** [comment]
@volans- +1

**Comment by peuh** [comment]
@jordansissel do you have an ETA for a new version installable via the repositories? I'm in the process of installing logstash forwarder on several servers, and I'd rather wait than have to install it manually if it's only a matter of hour before the release.

**Comment by burdandrei** [comment]
@peuh 
If you need the package you can download it [here](https://dl.dropboxusercontent.com/u/47137661/lsf/logstash-forwarder_0.3.1_amd64.deb), but the version is a bit obsolete, my advice is to compile what you need from master.

**Comment by peuh** [comment]
@burdandrei 
Yes if the package isn't planned to be released today I'll do my own .deb from sources and deploy it on the servers. It's just that I would have prefered to install it via aptitude so updates are done automatically when the package is updated. I'm not yet very comfortable with packaging of an app with it's default config, init.d scripts....

**Comment by andrewsomething** [comment]
@jordansissel Could you clarify what the bugs in the package are? Are these bugs in the v0.3.1 release or are they specific to the packages from that repository. Is using master recommended? It's been quite awhile since there was a tagged release.

Getting this into Debian and Ubuntu proper would be great, but unfortunately the vendorized libraries will make that a bit hard. I'd be willing to help maintain a more policy compliant package, I suppose I'll create a PPA if needed.

Just trying to figure out if the problems were in the packaging or in keeping up with changes, or?

Thanks!

**Comment by geerlingguy** [comment]
FYI this is also breaking [my logstash-forwarder Ansible role](https://github.com/geerlingguy/ansible-role-logstash-forwarder/blob/master/tasks/setup-Debian.yml#L9), which is used by a number of people to get logstash-forwarder up and running via Ansible (similar to Puppet module above).

I can't underscore the importance of an official repository (or at least a maintained repository) enough—I can (and may be forced to) switch to compiling manually, but I'm always much more comfortable using infrastructure tools that have a maintained repository, at least for the most popular distributions. It takes away some of the maintenance burden and fits nicely into the rest of my package management workflow.

**Comment by jordansissel** [comment]
* I am sorry that my actions have caused you all trouble.
* I understand it has broken things for some folks.
* We will do a release of lsf soon which includes a new package and an updated repo soon. 
* In the meantime, I invite you to build from master instead.

**Comment by volans-** [comment]
@jordansissel thanks for the answer, but this is the best way to loose lot of users.

Of course people can build the package by himself, and most of us will probably do it, but I think that none of us will like to build it from an unstable (by definition) master branch that can change and be broken at any point.

Given that none of us has any idea if _soon_ means hour, days, weeks or months, could you please at least in the meanwhile make a release with the latest existing commit that you consider stable and tested?
This will help people to build it in a more reliable way until the new release will be done.

**Comment by jordansissel** [comment]
@volans- "master" has no such "unstable" definition.

Doing a release isn't just "make a package and upload it somewhere" - if this is your belief, then you should know that this directly contradicts your view that master is defined as unstable.

**Comment by jordansissel** [comment]
@volans- if my apology is unacceptable to you, I understand your position. I am still aware of your concerns. Thank you for noting them again.

**Comment by jordansissel** [comment]
> make a release with the latest existing commit that you consider stable and tested

This is the 'master' branch.

**Comment by nornagon** [comment]
Is there an ETA on this or should I redo this section of my deployment infrastructure to not depend on the repository?

**Comment by geerlingguy** [comment]
@jordansissel - No problem, things like this do happen from time to time, and we appreciate the work you've done/are doing to help get logstash-forwarder easy to install and deploy! Please keep us updated here when you can :)

**Comment by volans-** [comment]
@jordansissel I may have not explain myself well, what I meant with doing a release was just mark it in GitHub with a release tag or branch. Without creating a new package for it.

Master is of course "stable" but not fixed in time, and, depending on your release process, before making a release from master I assume it will be "freezed" and tested.

But of course is just a proposal.

**Comment by stanhu** [comment]
FYI, I would advise everyone to retest their SSL certs with a master build of logstash-forwarder before  blindly using the new apt repository when it is released. I ran into this issue:

https://github.com/elasticsearch/logstash-forwarder/issues/226

**Comment by miliauskaite** [comment]
y u break my cookbook :(

**Comment by jverhoeven** [comment]
Please give us an ETA on when the package is back. I guess I am not the only one struggling with the right Go version and fpm dependencies right now.

**Comment by mvisonneau** [comment]
:+1:

**Comment by livejames** [comment]
Thank you for keeping a repo running at no cost to me. I'll just keep a local backup on a private repo in case this happens again.

**Comment by davedash** [comment]
FYI - if people want a "free" way of working around this, here's what I did.

I ran `make fpm` and uploaded the package to a public apt repo I made on
packagecloud.io.

It is actually probably for the best that I did this, just because relying
on "third party" repos isn't always a good idea.

**Comment by deviantony** [comment]
Also please note that I cannot build the package using `make deb` on Ubuntu 14.04.

````
$:~/logstash-forwarder$ make deb
pleaserun --install --no-install-actions --install-prefix ./build \
		--overwrite -p sysv -v lsb-3.1 /opt/logstash-forwarder/bin/logstash-forwarder 
make: pleaserun: Command not found
make: *** [generate-init-script] Error 127

````

And if I try to install pleaserun :

````
$ sudo gem install pleaserun
ERROR:  Error installing pleaserun:
	mustache requires Ruby version ~> 2.0.
````

**Comment by amosshapira** [comment]
@deviantony +1 for not being able to compile the package myself, I just hit the same problems myself.

I'm now stuck without a way to rebuild our Vagrant Basebox. I'll have to somehow recover the package from an existing box and setup our own repo mirror (I'm aware that this is supposed to be a buggy version but it works for us and I don't see a reasonable alternative, this is a far deeper rabbit hole than I intended to dig).

**Comment by PSiAU** [comment]
You can grab the package from the dropbox account belonging to @burdandrei (thank you!). What I ended up doing was installing the 0.3.1 package, then substituting the logstash-forwarder binary with my own built version from the master branch. That way the logstash-forwarder install is semi managed but running the latest binary.

**Comment by RBLU** [comment]
+1 

this small issue breaks basically all our ansible playbooks because "aptitude update" fails with 404, so I now need to remove this repo from the sources.list of all machines before I can install any updates again.  Will do that now, but would also be very grateful for a new repo we can point to. 
Thanks for your good work anyway.

**Comment by electrical** [comment]
Hi all,

We are working hard on getting LSF ready for a new release.
Once that's done we will re-activate the repo's again.

**Comment by JDiPierro** [comment]
Thanks for the update electrical. Just found this today when deploying a new server and installing logstash-forwarder failed :( Looking forward to the new release.

**Comment by astromoose** [comment]
@electrical looking forward to it :+1:

**Comment by pnegahdar** [comment]
@electrical thanks for the update. Any eta on reactivating the repo? Our builds relied on it.

**Comment by DukeZeppelin** [comment]
think whould really good if appear possibility to choose default path for config file 
 And leave this file editable before making "make rpm" 
it really whould be great!

**Comment by Siljanovski** [comment]
Hi guys, any news, eta or something ?

**Comment by adamcloneless** [comment]
This one bit me hard yesterday.

*The clear take away for a user is to mirror everything that's mission critical, if you aren't already.*

@jordansissel and all other contributors: Thank you for your work on this and for providing a repo. It's a huge help in getting it (and logstash in general) deployed.

My two cents, in the hope of providing some constructive criticism:

If we want people to treat this as a critical part of their infrastructure (and thus integrate it into their deployment scheme), being able to count on the deploy process is incredibly important. In the future, especially with repositories or anything that is a potential dependency for deployment, it would be a huge help to make sure that changes are either: a) non-breaking or b) publicly notified far in advance of a breaking change.

Just my opinion, but I think that creating a new repository would have been a much better option based on what we know so far about the reasons for the change (though I acknowledge that there may be factors that have not come to light yet). After establishing a working, opt-in alternative and providing a reasonable notification period, it would be okay to kill the current repo, redirect it, or replace it.

Taking a very considered approach to breaking changes is important in being a steward of any public-facing software. I think the fact that this change affected so many people testifies to the fact that logstash-forwarder and the people contributing to it are doing important (and hopefully appreciated) work. With some additional process in place, this should be something that can be avoided in the future.

It'd be nice, once a fix is in place, to do a post-mortem so that there are some concrete steps that people can plan on in the future.

I think we all learned a lot, hopefully with out too much long term pain.

Thanks again for the work you're doing.

**Comment by TimmGr** [comment]
Hallo everybody,

the last couple of weeks I was busy setting up a Logging Environment at work. It is a feasibility study on how to avoid splunk.
I was following this tutorial: https://www.digitalocean.com/community/tutorials/how-to-use-logstash-and-kibana-to-centralize-and-visualize-logs-on-ubuntu-14-04
Note that I am no serveradmin by profession and consequently it took me a considerable amount of time.

Just as I am about to tell the team, that we can go with the logstash-graylog combo, the repository goes offline. Well, that was a little bit embarrassing for me :)

But I do not want to be the one who is complaining: Thank you for your hard work. Your software is cool. And will be even cooler, as soon as you make the installation fool-proof again.

Cheers

Oh one more thing: While installing it on Windows i spend a lot of time on the question on how to configure the paths (you have to use double \\). Finally I found the answer, well hidden on:
https://logstash.jira.com/browse/LOGSTASH-1856
Maybe you want to present that also in the documentation. In case that is common knowledge please ignore this.

**Comment by zabbal** [comment]
> If you can't maintain it I think you could simply ask the Debian Developers / Ubuntu MOTU teams to try to get an official maintainer for the DEB packages.

That would require fixing #299 with the help of lintian tool.

**Comment by mattwilliamson** [comment]
Dude. Killed so many deployments.

**Comment by brendangibat** [comment]
+1

**Comment by jordansissel** [comment]
#285 tracks the package repository.

**Comment by JDiPierro** [comment]
#385 actually.

**Comment by missgonads** [comment]
wtf?? still no package and don't want to build.  Going to use Fluentd instead!

**Comment by mahnunchik** [comment]
Can anyone in this thread provide a list of alternatives to `logstash-forwarder` with a more sensible approach to releases?

**Comment by Siljanovski** [comment]
Gents, I know this is not a long-term solution but it helped me a lot:
Here you can find one .sh file (I am not sys-admin so my bash scripting is basic).
https://github.com/Siljanovski/elasticsearch/blob/master/logstash-forwarder-installer.sh

I used this for installing manually, but with little modification you can put this into Chef or any other config management tool that you use. 
I put both daemon script file and deb file for 64 bits into my repo since they were gone from other repos that I was using before. I will not remove them :)

The only thing that you need to do is to give access to your servers so they can scp the crt file and that's it. It works just after executing this script.

This might help you a bit.

**Comment by driskell** [comment]
@mahnunchik I maintain an alternative called [Log Courier](https://github.com/driskell/log-courier) - it doesn't have Deb or rpm at moment but will have CentOS/RedHat rpm soon. Not had any demand for Deb as such.

**Comment by deviantony** [comment]
@driskell 's alternative is great but it also lack the presence of a debian repository, which is mainly why I didn't switch to it.

**Comment by pnegahdar** [comment]
@Siljanovski yup, pretty much what I'm doing. Careful with the the wget on master you should use "https://github.com/elasticsearch/logstash-forwarder/archive/v0.3.1.tar.gz" instead. Also the touch should be unnecessary with the `echo >` creates if DNE.

**Comment by amosshapira** [comment]
What I ended up doing for now is to salvage a copy of the .deb file from the cache of one of our running servers and build a repository around it on S3 using reprepro. Eventually I'll get around to mirror all such "small" external repositories we use, and would recommend everyone else to do the same.

If you need a copy of the repository then let me know how you want me to get it to you.
