### ISSUE TITLE
Broken deb source URL

### ISSUE THREAD

**Issue by swaroopkundeti** [elasticsearch/logstash-forwarder#370]
Unable to update package manager after adding deb source to source list 

<pre>
Fetched 4,510 kB in 2s (1,589 kB/s)
W: Failed to fetch http://packages.elasticsearch.org/logstashforwarder/debian/dists/stable/main/binary-amd64/Packages  404  Not Found [IP: 23.23.158.216 80]

W: Failed to fetch http://packages.elasticsearch.org/logstashforwarder/debian/dists/stable/main/binary-i386/Packages  404  Not Found [IP: 23.23.158.216 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
</pre>

**Comment by jbianquetti** [comment]
+1

**Comment by jordansissel** [comment]
The repository you refer to was never intended to be for production; it was setup as a test a year ago and forgotten about. I noticed this and removed it last weekend.

We will be putting a supported apt repo online soon with the next release of lsf.

**Comment by evanccopengeo** [comment]
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/setup-repositories.html Any idea why this is referenced in this documentation then?

**Comment by evanccopengeo** [comment]
They all seemed to have disappeared at once.

**Comment by jbianquetti** [comment]
That's true. If docs point this repos as a trusted source, several of us
prefer a developer trusted build  instead source code compilation, and
breaking provision process its a production problem for us.

**Comment by driskell** [comment]
@evanccopengeo Those docs only refer to Elasticsearch repository and not this forwarder one. Searching forwarder on the page finds nothing.

**Comment by jordansissel** [comment]
Hyperbole has taken over, I suppose. I'll address things.

> why this is referenced in this documentation then?

Please read this document more carefully. It ONLY refers to the 'elasticsearch' repository. It doesn't mention logstash or logstash forwarder anywhere on the page.

> They all seemed to have disappeared at once.

Please provide data. I tested the repos (logstash, elasticsearch) and all are functioning as expected. If you find otherwise, please provide specific data.

> If docs point this repos as a trusted source

The docs, again, do not point at logstash forwarder repo.

> a developer trusted build

You'll need to define what "developer trusted build" means, for me. I do not believe we have such a phrase anywhere in our documentation in reference to the package repositories.

> instead source code compilation

Our packages are built from source. We do not inject any magical power at compilation time that would cause your build to deviate significantly from ours.

> breaking provision process its a production problem for us

I understand. Please understand that everyone involved in this situation is human, and as a result, is capable of making mistakes.

I deleted a repository I thought to be unused and abandoned *because* so many users report that they some how stumbled across it, used it, and found it to have delivered poorly-functioning code. After many months of this, I decided it was worth deleting so that new users would not read some random blog post pointing them at a repository I didn't even know was used (and certainly wasn't documented or supported, best I can tell) and having them receive broken software.

I understand the impact this has had on many of you. Please watch the commits on this repository and see that I am actively working to resolve this problem.

**Comment by jordansissel** [comment]
I"ll put this in big text so folks who are tempted to comment may find they don't need to:

## WE ARE AWARE OF THE PROBLEM.
## WE ARE WORKING TO FIX IT.

**Comment by derdanu** [comment]
+1

**Comment by kevinprince** [comment]
+1

**Comment by yeukhon** [comment]
+1 this breaks everyone....

**Comment by rolandah** [comment]
+1

**Comment by ernetas** [comment]
@jordansissel is there an approximate estimate of how fast that will happen (days/weeks/months?) or should we switch to our local repos?

**Comment by jordansissel** [comment]
> this breaks everyone

Please only speak for yourself.

**Comment by jordansissel** [comment]
I"ll put this in big text, again, to make it more obvious. A summary:

## WE ARE AWARE OF THE PROBLEM.
## WE ARE WORKING TO FIX IT.

I am now locking this issue.

**Comment by jordansissel** [comment]
I unlocked after thinking about the implications.

Please, folks, understand that we will put up an actually-supported repository of logstash-forwarder soon. I do not have an ETA.

**Comment by jordansissel** [comment]
There is no need to +1 this ticket. We are aware of the problem. We are working on a solution.

**Comment by jordansissel** [comment]
#385 tracks the implementation of a package repository.

**Comment by ashwiniadlakha** [comment]
+1
Its ok jordansissel. Let us do +1. It will help other new users like me.
Just update when Its fixed. 

PS: you guys are going a great job and it has helped me alot :)
