### ISSUE TITLE
Failed to open syslog

### ISSUE THREAD

**Issue by Wolfsrudel** [elasticsearch/logstash-forwarder#79]
I've compiled lumberjack-go on a SuSE 11 system. When trying to install lumberjack on a SuSE 10 system, i'm getting the following error message:

"2013/09/09 11:52:33.095986 Failed to open syslog: Unix syslog delivery error
startproc:  exit status of parent of /opt/lumberjack/bin/lumberjack.sh: 1"

Do i have do compile an extra lumberjack-client for SuSE 10 on a SuSE 10 system?

**Comment by jordansissel** [comment]
I'm not exactly sure what the problem here was, sounds like some kind of syslog bug/problem integrating with SuSE? I don't know



I think this bug was for the C version of lumberjack, lsf is now in Go; I'm not sure it's affected anymore. Please reopen if you're still hitting this in the newer logstash-forwarder.
